version: 1.2
workflows:
  - subclass: WDL
    name: create_pca_projection
    primaryDescriptorPath: create_pca_projection.wdl
    authors: 
      - orcid: 0000-0002-7989-5420
    #testParameterFiles:
     #  - /projected_pca.json
  - subclass: WDL
    name: projected_PCA
    primaryDescriptorPath: projected_pca.wdl
    authors: 
      - orcid: 0000-00020-7989-5420
   # testParameterFiles:
   #   - /projected_pca.json
